In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('NB.csv',  encoding = 'ISO-8859-1')

In [3]:
df.head()

type                                               text
0   ham  Hope you are having a good week. Just checking in
1   ham                            K..give back my thanks.
2   ham        Am also doing in cbe only. But have to pay.
3  spam  complimentary 4 STAR Ibiza Holiday or å£10,000...
4  spam  okmail: Dear Dave this is your final notice to...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5559 entries, 0 to 5558
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   type    5559 non-null   object
 1   text    5559 non-null   object
dtypes: object(2)
memory usage: 87.0+ KB


In [5]:
df['type'].value_counts()

ham     4812
spam     747
Name: type, dtype: int64

In [6]:
import string
from nltk.corpus import stopwords
stp = stopwords.words('english')
stp


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [7]:
import re

In [8]:
import nltk
from nltk.stem import WordNetLemmatizer as wnl


In [9]:
import sklearn
pd.set_option('max_colwidth', 1000)

In [10]:
df.head()

type  \
0   ham   
1   ham   
2   ham   
3  spam   
4  spam   

                                                                                                                                                                text  
0                                                                                                                  Hope you are having a good week. Just checking in  
1                                                                                                                                            K..give back my thanks.  
2                                                                                                                        Am also doing in cbe only. But have to pay.  
3             complimentary 4 STAR Ibiza Holiday or å£10,000 cash needs your URGENT collection. 09066364349 NOW from Landline not to lose out! Box434SK38WP150PPM18+  
4  okmail: Dear Dave this is your final notice to collect your 4* Tenerife Holiday or #5000 CASH award! Call 09061743806 from landline. TCs SAE Box326 CW25WX 150ppm

In [11]:
nltk.download('wordnet')
def clean_text(text):
    data = [char for char in text if char not in string.punctuation]
    data = ''.join(data)
    words = re.sub(r"(@[A-Za-z0-9]+)|([^A-Za-z0-9 \t])|(\w+:\/\/\S+)|^rt|http.+?", " ", data )
    words = words.lower()
    final_words = [wnl().lemmatize(word, pos="v") for word in words.split()]
    final_words = ' '.join(final_words)
    return final_words

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [12]:
df['clean_data'] = df['text'].apply(clean_text)

In [13]:
df.head()

type  \
0   ham   
1   ham   
2   ham   
3  spam   
4  spam   

                                                                                                                                                                text  \
0                                                                                                                  Hope you are having a good week. Just checking in   
1                                                                                                                                            K..give back my thanks.   
2                                                                                                                        Am also doing in cbe only. But have to pay.   
3             complimentary 4 STAR Ibiza Holiday or å£10,000 cash needs your URGENT collection. 09066364349 NOW from Landline not to lose out! Box434SK38WP150PPM18+   
4  okmail: Dear Dave this is your final notice to collect your 4* Tenerife Holiday or #5000 CASH award! Call 09061743806 from landline. TCs SAE Box326 CW25WX 150ppm   

                                                                                                                                                     clean_data  
0                                                                                                                    hope you be have a good week just check in  
1                                                                                                                                           kgive back my thank  
2                                                                                                                        be also do in cbe only but have to pay  
3               complimentary 4 star ibiza holiday or 10000 cash need your urgent collection 09066364349 now from landline not to lose out box434sk38wp150ppm18  
4  okmail dear dave this be your final notice to collect your 4 tenerife holiday or 5000 cash award call 09061743806 from landline tcs sae box326 cw25wx 150ppm

In [14]:
x = str(df['text'][3])
x

'complimentary 4 STAR Ibiza Holiday or å£10,000 cash needs your URGENT collection. 09066364349 NOW from Landline not to lose out! Box434SK38WP150PPM18+'

In [15]:
clean_text(x)

'complimentary 4 star ibiza holiday or 10000 cash need your urgent collection 09066364349 now from landline not to lose out box434sk38wp150ppm18'

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
cv = CountVectorizer()
bag_words = cv.fit(df['clean_data'])

In [18]:
bag_words.get_feature_names()

['008704050406',
 '0089my',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '020603',
 '0207',
 '02070836089',
 '02072069400',
 '02073162414',
 '02085076972',
 '020903',
 '021',
 '050703',
 '0578',
 '06',
 '060505',
 '061104',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '071104',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '0784987',
 '0789xxxxxxx',
 '0794674629107880867867',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073'

In [19]:
bag_words = bag_words.transform(df['clean_data'])

In [20]:
bag_words.shape

(5559, 8514)

In [21]:
df.shape

(5559, 3)

In [22]:
X = pd.DataFrame(data = bag_words.toarray())

In [23]:
X

0     1     2     3     4     5     6     7     8     9     ...  8504  \
0        0     0     0     0     0     0     0     0     0     0  ...     0   
1        0     0     0     0     0     0     0     0     0     0  ...     0   
2        0     0     0     0     0     0     0     0     0     0  ...     0   
3        0     0     0     0     0     0     0     0     0     0  ...     0   
4        0     0     0     0     0     0     0     0     0     0  ...     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
5554     0     0     0     0     0     0     0     0     0     0  ...     0   
5555     0     0     0     0     0     0     0     0     0     0  ...     0   
5556     0     0     0     0     0     0     0     0     0     0  ...     0   
5557     0     0     0     0     0     0     0     0     0     0  ...     0   
5558     0     0     0     0     0     0     0     0     0     0  ...     0   

      8505  8506  8507  8508  8509  8510  8511  8512  8513  
0        0     0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
5554     0     0     0     0     0     0     0     0     0  
5555     0     0     0     0     0     0     0     0     0  
5556     0     0     0     0     0     0     0     0     0  
5557     0     0     0     0     0     0     0     0     0  
5558     0     0     0     0     0     0     0     0     0  

[5559 rows x 8514 columns]

In [24]:
df['type'].replace(to_replace = ['spam','ham'] , value = [1,0] , inplace = True)
y = df['type']
df['type'].value_counts()


0    4812
1     747
Name: type, dtype: int64

In [25]:
import pickle
pickle.dump(cv, open("vector_f.pkl", "wb"))
CV = pickle.load(open("vector_f.pkl", 'rb'))
CV


CountVectorizer()

In [26]:
var = df['clean_data'].iloc[3]
var  = [var]

In [27]:
var

['complimentary 4 star ibiza holiday or 10000 cash need your urgent collection 09066364349 now from landline not to lose out box434sk38wp150ppm18']

In [28]:
bag =CV.transform(var).toarray()
bag.shape


(1, 8514)

In [29]:
bag

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
from sklearn.model_selection import StratifiedShuffleSplit

sss = StratifiedShuffleSplit(n_splits=1, test_size=0.1, random_state=0)
print(sss.get_n_splits(X, y))
print(sss)

train_idx = 0
test_idx = 0
for train_idx , test_idx in sss.split(X,y):
    X_train  , X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train  , y_test = y.iloc[train_idx], y.iloc[test_idx]


1
StratifiedShuffleSplit(n_splits=1, random_state=0, test_size=0.1,
            train_size=None)


In [31]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(y.value_counts())
print(y_train.value_counts())
print(y_test.value_counts())


(5003, 8514)
(556, 8514)
(5003,)
(556,)
0    4812
1     747
Name: type, dtype: int64
0    4331
1     672
Name: type, dtype: int64
0    481
1     75
Name: type, dtype: int64


In [32]:
from sklearn.svm import SVC


In [33]:
clf = SVC(class_weight = 'balanced')


clf.fit(X_train, y_train)


SVC(class_weight='balanced')

In [34]:
predict = clf.predict(X_train)

In [35]:
predict

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [36]:
expected = y_train

from sklearn import metrics
print(metrics.classification_report(expected, predict))
print(metrics.confusion_matrix(expected, predict))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4331
           1       1.00      1.00      1.00       672

    accuracy                           1.00      5003
   macro avg       1.00      1.00      1.00      5003
weighted avg       1.00      1.00      1.00      5003

[[4329    2]
 [   2  670]]


In [37]:
predicted = clf.predict(X_test)
expected = y_test

from sklearn import metrics
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))


              precision    recall  f1-score   support

           0       0.98      1.00      0.99       481
           1       0.98      0.84      0.91        75

    accuracy                           0.98       556
   macro avg       0.98      0.92      0.95       556
weighted avg       0.98      0.98      0.98       556

[[480   1]
 [ 12  63]]


In [38]:
pickle.dump(clf, open("model.pkl", "wb"))
model = pickle.load(open("model.pkl", 'rb'))
model

SVC(class_weight='balanced')

In [39]:
model.predict(bag)

array([1], dtype=int64)

In [40]:
import gzip, pickle
with gzip.open('model_2.pkl', 'wb') as ofp:
    pickle.dump(clf, ofp)


In [41]:
with gzip.open('model_2.pkl', 'rb') as ifp:
    m = pickle.load(ifp)



In [42]:
m.predict(bag)

array([1], dtype=int64)

In [43]:
message  = str('okmail: Dear Dave this is your final notice to collect your 4* Tenerife Holiday or #5000 CASH award! Call 09061743806 from landline. TCs SAE Box326 CW25WX 150ppm')
data = [message]
data_clean = clean_text(data)
data_clean = [data_clean]
vect = CV.transform(data_clean).toarray()
my_prediction = m.predict(vect)
        


In [44]:
my_prediction

array([1], dtype=int64)